image: node:14.15.4

clone:
    depth: full

definitions:
    services:
        postgres:
            image: sameersbn/postgresql:latest
            environment:
                DB_USER: developer
                DB_PASS: developer
                DB_NAME: silvernext_api_test
                DB_EXTENSION: '"uuid-ossp"'

installDependencies: &installDependencies
    step:
        name: 🛠 Install node modules
        script:
            - npm install
        caches:
            - node

build: &build
    step:
        name: 🛠 Build
        caches:
            - node
        script:
            - yarn build

lint: &lint
    step:
        name: 🧹 Linting
        caches:
            - node
        script:
            - yarn lint

format: &format
    step:
        name: 🧹 Formatting
        caches:
            - node
        script:
            - yarn format:check

runTests: &runTests
    step:
        name: 🔬 Tests
        caches:
            - node
        script:
            - yarn db:migrate
            - yarn db:seed:all
            - yarn test
        services:
            - postgres

pipelines:
    pull-requests:
        '**': #this runs as default for any branch not elsewhere defined
            - <<: *installDependencies
            - parallel:
                  - <<: *build
                  - <<: *format
                  - <<: *lint
                  - <<: *runTests
    branches:
        master:
            - <<: *installDependencies
            - parallel:
                  - <<: *build
                  - <<: *format
                  - <<: *lint
                  - <<: *runTests
            - step:
                  name: 🚀 Deploy to develop
                  deployment: develop
                  script:
                      - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git HEAD:master
        release/**:
            - <<: *installDependencies
            - parallel:
                  - <<: *build
                  - <<: *format
                  - <<: *lint
                  - <<: *runTests
            - step:
                  name: 🚀 Deploy to staging
                  deployment: staging
                  trigger: manual
                  script:
                      - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git HEAD:master
            - step:
                  name: 🚀 Deploy to production
                  deployment: production
                  trigger: manual
                  script:
                      - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git HEAD:master
