version: '3.3'
services:
    postgres:
        image: sameersbn/postgresql:latest
        container_name: pgsql_silvernext
        ports:
            - '5432:5432'
        env_file:
            - ./.env.local
        volumes:
            - ./../data/postgres:/var/lib/postgresql/data
